// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmrygkfxnzuxkgnybkec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtcnlna2Z4bnp1eGtnbnlia2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTAzMTMsImV4cCI6MjA2OTEyNjMxM30.WU0ckHacd8no5GUIjdySke1jwo1ol-6k_sVr37Nxzzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});